2025-05-01 15:44:01,984 - INFO - Starting task ID 7 for application 1176978325
2025-05-01 15:44:09,661 - INFO - 1176978325 24-03-2007 LMV,MCWG 10-11-2025   TRUE 1
2025-05-01 15:44:09,661 - INFO - 
2025-05-01 15:44:09,661 - INFO - Time reached: Starting the code...
2025-05-01 15:44:09,661 - INFO - 
2025-05-01 15:44:09,666 - INFO - 
2025-05-01 15:44:09,666 - INFO - Selected Proxy: {}
2025-05-01 15:44:09,666 - INFO - {}
2025-05-01 15:44:09,666 - INFO - start
2025-05-01 15:44:10,256 - INFO - making request to createTask
2025-05-01 15:44:11,178 - INFO - created task with id 39809494
2025-05-01 15:44:12,184 - INFO - making request to getTaskResult
2025-05-01 15:44:17,466 - INFO - task is still processing
2025-05-01 15:44:18,472 - INFO - making request to getTaskResult
2025-05-01 15:44:23,935 - INFO - task is still processing
2025-05-01 15:44:24,945 - INFO - making request to getTaskResult
2025-05-01 15:44:25,308 - INFO - task solved
2025-05-01 15:44:25,308 - INFO - captcha text 4b50aF
2025-05-01 15:44:25,308 - INFO - 4b50aF
2025-05-01 15:44:26,007 - INFO - Captcha success
2025-05-01 15:44:26,533 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:26,533 - INFO - start
2025-05-01 15:44:27,140 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:27,140 - INFO - start
2025-05-01 15:44:27,818 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:27,819 - INFO - start
2025-05-01 15:44:28,389 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:28,389 - INFO - start
2025-05-01 15:44:28,916 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:28,916 - INFO - start
2025-05-01 15:44:29,530 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:29,530 - INFO - start
2025-05-01 15:44:30,078 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:30,078 - INFO - start
2025-05-01 15:44:30,662 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:30,662 - INFO - start
2025-05-01 15:44:31,214 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:31,214 - INFO - start
2025-05-01 15:44:31,831 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:31,832 - INFO - start
2025-05-01 15:44:32,412 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:32,412 - INFO - start
2025-05-01 15:44:32,970 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:32,971 - INFO - start
2025-05-01 15:44:33,581 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:33,581 - INFO - start
2025-05-01 15:44:34,096 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:34,097 - INFO - start
2025-05-01 15:44:34,655 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:34,655 - INFO - start
2025-05-01 15:44:35,264 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:35,265 - INFO - start
2025-05-01 15:44:35,874 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:35,874 - INFO - start
2025-05-01 15:44:36,484 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:36,484 - INFO - start
2025-05-01 15:44:37,148 - INFO - name 'proceeddata' is not defined
2025-05-01 15:44:37,148 - INFO - start
2025-05-01 15:44:37,521 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,521 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,521 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,522 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,522 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,522 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,522 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,523 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,523 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,523 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,523 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,523 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,523 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,524 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,524 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,524 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,524 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,524 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,524 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,525 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,525 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,525 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,525 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,525 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,525 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,526 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,526 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,526 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,526 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,527 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,527 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,527 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,528 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,528 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,528 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,528 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,528 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,529 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,529 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,529 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,529 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,529 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,529 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,530 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,530 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,530 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,530 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,530 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,531 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,531 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,531 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,531 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,531 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,531 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,531 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,532 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,532 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,532 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,532 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,532 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,532 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,532 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,533 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,533 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,533 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,533 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,533 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,534 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,534 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,534 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,534 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,534 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,534 - ERROR - Traceback (most recent call last):
2025-05-01 15:44:37,535 - ERROR - File "C:\Users\User\Downloads\DLPROJ\game.py", line 310, in <module>
2025-05-01 15:44:37,535 - ERROR - purp0_data = proceeddata
2025-05-01 15:44:37,535 - ERROR - NameError: name 'proceeddata' is not defined
2025-05-01 15:44:37,557 - INFO - Task ID 7 status updated to Failed
